[package]
name = "gol"
version = "0.1.0"
authors = ["Ezequiel Garcia <ezequiel@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
grid = "0.3"
rand = "0.8.3"
